const $prefix = "app/onchain/";
const MODAL_STATE_SEND_COINS = `${$prefix}MODAL_STATE_SEND_COINS`;
const MODAL_STATE_WARNING = `${$prefix}MODAL_STATE_WARNING`;
const SET_ONCHAIN_HISTORY = `${$prefix}SET_ONCHAIN_HISTORY`;
const SEND_COINS_PREPARING = `${$prefix}SEND_COINS_PREPARING`;
const CLEAR_SEND_COINS_PREPARING = `${$prefix}CLEAR_SEND_COINS_PREPARING`;
const SET_ONCHAIN_FEE = `${$prefix}SET_ONCHAIN_FEE`;
const SET_SEND_COINS_PAYMENT_DETAILS = `${$prefix}SET_SEND_COINS_PAYMENT_DETAILS`;

export {
    MODAL_STATE_SEND_COINS,
    MODAL_STATE_WARNING,
    SET_ONCHAIN_HISTORY,
    SEND_COINS_PREPARING,
    CLEAR_SEND_COINS_PREPARING,
    SET_ONCHAIN_FEE,
    SET_SEND_COINS_PAYMENT_DETAILS,
};
