const $prefix = "app/account/";
export const CREATE_ACCOUNT = `${$prefix}CREATE_ACCOUNT`;
export const SUCCESS_CREATE_NEW_ACCOUNT = `${$prefix}SUCCESS_CREATE_NEW_ACCOUNT`;
export const ERROR_CREATE_NEW_ACCOUNT = `${$prefix}ERROR_CREATE_NEW_ACCOUNT`;
export const SET_LIGHTNING_ID = `${$prefix}SET_LIGHTNING_ID`;
export const LOGIN_ACCOUNT = `${$prefix}LOGIN_ACCOUNT`;
export const ERROR_AUTH_ON_SERVER = `${$prefix}ERROR_AUTH_ON_SERVER`;
export const START_INIT_ACCOUNT = `${$prefix}START_INIT_ACCOUNT`;
export const FINISH_INIT_ACCOUNT = `${$prefix}FINISH_INIT_ACCOUNT`;
export const LOGOUT_ACCOUNT = `${$prefix}LOGOUT_ACCOUNT`;
export const SUCCESS_LOGOUT_ACCOUNT = `${$prefix}SUCCESS_LOGOUT_ACCOUNT`;
export const START_LOGOUT = `${$prefix}START_LOGOUT`;
export const FINISH_LOGOUT = `${$prefix}FINISH_LOGOUT`;
export const ERROR_CONNECT_KERNEL = `${$prefix}FAIL_CONNECT_KERNEL`;
export const SUCCESS_CONNECT_KERNEL = `${$prefix}SUCCESS_CONNECT_KERNEL`;
export const SUCCESS_SIGN_MESSAGE = `${$prefix}SUCCESS_SIGN_MESSAGE`;
export const SET_CONNECTED_KERNEL_CONNECT_INDICATOR = `${$prefix}SET_CONNECTED_KERNEL_CONNECT_INDICATOR`;
export const SET_DISCONNECTED_KERNEL_CONNECT_INDICATOR = `${$prefix}SET_DISCONNECTED_KERNEL_CONNECT_INDICATOR`;
export const SET_PEERS = `${$prefix}SET_PEERS`;
export const ERROR_PEERS = `${$prefix}ERROR_PEERS`;
export const ADD_BITCOIN_ACCOUNT = `${$prefix}ADD_BITCOIN_ACCOUNT`;
export const SUCCESS_SEND_BTC_TO_ADDRESS = `${$prefix}SUCCESS_SEND_BTC_TO_ADDRESS`;
export const ERROR_SEND_BTC_TO_ADDRESS = `${$prefix}ERROR_SEND_BTC_TO_ADDRESS`;
export const SUCCESS_GENERATE_QR_CODE = `${$prefix}SUCCESS_GENERATE_QR_CODE`;
export const SET_BITCOIN_MEASURE = `${$prefix}SET_BITCOIN_MEASURE`;
export const CORRECT_LIGHTNING_ID = `${$prefix}CORRECT_LIGHTNING_ID`;
export const INCORRECT_LIGHTNING_ID = `${$prefix}INCORRECT_LIGHTNING_ID`;
export const UNDEFINED_LIGHTNING_ID = `${$prefix}UNDEFINED_LIGHTNING_ID`;
export const START_VALIDATING_LIGHTNING_ID = `${$prefix}START_VALIDATING_LIGHTNING_ID`;
export const END_VALIDATING_LIGHTNING_ID = `${$prefix}END_VALIDATING_LIGHTNING_ID`;
export const INCORRECT_PAYMENT_AMOUNT = `${$prefix}INCORRECT_PAYMENT_AMOUNT`;
export const CORRECT_PAYMENT_AMOUNT = `${$prefix}CORRECT_PAYMENT_AMOUNT`;
export const UNDEFINED_PAYMENT_AMOUNT = `${$prefix}UNDEFINED_PAYMENT_AMOUNT`;
export const SUCCESS_CHECK_BALANCE = `${$prefix}SUCCESS_CHECK_BALANCE`;
export const ERROR_CHECK_BALANCE = `${$prefix}ERROR_CHECK_BALANCE`;
export const SET_LIS_STATUS = `${$prefix}SET_LIS_STATUS`;
export const LIS_NONE = `${$prefix}LIS_NONE`;
export const LIS_DOWN = `${$prefix}LIS_DOWN`;
export const LIS_UP = `${$prefix}LIS_UP`;
export const KERNEL_DISCONNECTED = `${$prefix}KERNEL_DISCONNECTED`;
export const KERNEL_CONNECTED = `${$prefix}KERNEL_CONNECTED`;
export const SET_SYSTEM_NOTIFICATIONS_STATUS = `${$prefix}SET_SYSTEM_NOTIFICATIONS_STATUS`;
export const MODAL_STATE_SYSTEM_NOTIFICATIONS = `${$prefix}MODAL_STATE_SYSTEM_NOTIFICATIONS`;
export const MODAL_STATE_WALLET_MODE = `${$prefix}MODAL_STATE_WALLET_MODE`;
export const MODAL_STATE_TERMS_AND_CONDITIONS = `${$prefix}MODAL_STATE_TERMS_AND_CONDITIONS`;
export const SET_ANALYTICS_MODE = `${$prefix}SET_ANALYTICS_MODE`;
export const SET_WALLET_MODE = `${$prefix}SET_WALLET_MODE`;
export const SET_TERMS_MODE = `${$prefix}SET_TERMS_MODE`;

export const NOTIFICATIONS = {
    DISABLED_LOUD_DONT_SHOW_AGAIN: 2,
    DISABLED_LOUD_SHOW_AGAIN: 3,
    DISABLED_SILENT_DONT_SHOW_AGAIN: 0,
    DISABLED_SILENT_SHOW_AGAIN: 1,
    ENABLED_LOUD_DONT_SHOW_AGAIN: 6,
    ENABLED_LOUD_SHOW_AGAIN: 7,
    ENABLED_SILENT_DONT_SHOW_AGAIN: 4,
    ENABLED_SILENT_SHOW_AGAIN: 5,
};
export const WALLET_MODE = {
    EXTENDED: "extended",
    PENDING: null,
    STANDARD: "standard",
};
export const WALLET_MODES_LIST = [
    WALLET_MODE.EXTENDED,
    WALLET_MODE.PENDING,
    WALLET_MODE.STANDARD,
];
export const ANALYTICS_MODE = {
    DISABLED: "disabled",
    ENABLED: "enabled",
    PENDING: null,
};
export const ANALYTICS_MODES_LIST = [
    ANALYTICS_MODE.ENABLED,
    ANALYTICS_MODE.DISABLED,
    ANALYTICS_MODE.PENDING,
];
export const TERMS_MODE = {
    ACCEPTED: 1,
    PENDING: 0,
};
export const TERMS_MODES_LIST = [
    TERMS_MODE.ACCEPTED,
    TERMS_MODE.PENDING,
];

export const CHANNELS_INTERVAL_ID = `${$prefix}CHANNELS_INTERVAL_ID`;
export const BALANCE_INTERVAL_ID = `${$prefix}BALANCE_INTERVAL_ID`;
export const USD_PER_BTC_INTERVAL_ID = `${$prefix}USD_PER_BTC_INTERVAL_ID`;
export const LND_SYNC_STATUS_INTERVAL_ID = `${$prefix}LND_SYNC_STATUS_INTERVAL_ID`;
export const GET_MERCHANTS_INTERVAL_ID = `${$prefix}GET_MERCHANTS_INTERVAL_ID`;
