const $prefix = "app/account/";
const CREATE_ACCOUNT = `${$prefix}CREATE_ACCOUNT`;
const SUCCESS_CREATE_NEW_ACCOUNT = `${$prefix}SUCCESS_CREATE_NEW_ACCOUNT`;
const ERROR_CREATE_NEW_ACCOUNT = `${$prefix}ERROR_CREATE_NEW_ACCOUNT`;
const SET_LIGHTNING_ID = `${$prefix}SET_LIGHTNING_ID`;
const LOGIN_ACCOUNT = `${$prefix}LOGIN_ACCOUNT`;
const ERROR_AUTH_ON_SERVER = `${$prefix}ERROR_AUTH_ON_SERVER`;
const START_INIT_ACCOUNT = `${$prefix}START_INIT_ACCOUNT`;
const FINISH_INIT_ACCOUNT = `${$prefix}FINISH_INIT_ACCOUNT`;
const LOGOUT_ACCOUNT = `${$prefix}LOGOUT_ACCOUNT`;
const SUCCESS_LOGOUT_ACCOUNT = `${$prefix}SUCCESS_LOGOUT_ACCOUNT`;
const START_LOGOUT = `${$prefix}START_LOGOUT`;
const FINISH_LOGOUT = `${$prefix}FINISH_LOGOUT`;
const ERROR_CONNECT_KERNEL = `${$prefix}FAIL_CONNECT_KERNEL`;
const SUCCESS_CONNECT_KERNEL = `${$prefix}SUCCESS_CONNECT_KERNEL`;
const SUCCESS_SIGN_MESSAGE = `${$prefix}SUCCESS_SIGN_MESSAGE`;
const SET_CONNECTED_KERNEL_CONNECT_INDICATOR = `${$prefix}SET_CONNECTED_KERNEL_CONNECT_INDICATOR`;
const SET_DISCONNECTED_KERNEL_CONNECT_INDICATOR = `${$prefix}SET_DISCONNECTED_KERNEL_CONNECT_INDICATOR`;
const SET_PEERS = `${$prefix}SET_PEERS`;
const ERROR_PEERS = `${$prefix}ERROR_PEERS`;
const ADD_BITCOIN_ACCOUNT = `${$prefix}ADD_BITCOIN_ACCOUNT`;
const SUCCESS_SEND_BTC_TO_ADDRESS = `${$prefix}SUCCESS_SEND_BTC_TO_ADDRESS`;
const ERROR_SEND_BTC_TO_ADDRESS = `${$prefix}ERROR_SEND_BTC_TO_ADDRESS`;
const SUCCESS_GENERATE_QR_CODE = `${$prefix}SUCCESS_GENERATE_QR_CODE`;
const SET_BITCOIN_MEASURE = `${$prefix}SET_BITCOIN_MEASURE`;
const CORRECT_LIGHTNING_ID = `${$prefix}CORRECT_LIGHTNING_ID`;
const INCORRECT_LIGHTNING_ID = `${$prefix}INCORRECT_LIGHTNING_ID`;
const UNDEFINED_LIGHTNING_ID = `${$prefix}UNDEFINED_LIGHTNING_ID`;
const START_VALIDATING_LIGHTNING_ID = `${$prefix}START_VALIDATING_LIGHTNING_ID`;
const END_VALIDATING_LIGHTNING_ID = `${$prefix}END_VALIDATING_LIGHTNING_ID`;
const INCORRECT_PAYMENT_AMOUNT = `${$prefix}INCORRECT_PAYMENT_AMOUNT`;
const CORRECT_PAYMENT_AMOUNT = `${$prefix}CORRECT_PAYMENT_AMOUNT`;
const UNDEFINED_PAYMENT_AMOUNT = `${$prefix}UNDEFINED_PAYMENT_AMOUNT`;
const SET_MAXIMUM_PAYMENT = `${$prefix}SET_MAXIMUM_PAYMENT`;
const SUCCESS_CHECK_BALANCE = `${$prefix}SUCCESS_CHECK_BALANCE`;
const ERROR_CHECK_BALANCE = `${$prefix}ERROR_CHECK_BALANCE`;
const SET_LIS_STATUS = `${$prefix}SET_LIS_STATUS`;
const LIS_NONE = `${$prefix}LIS_NONE`;
const LIS_DOWN = `${$prefix}LIS_DOWN`;
const LIS_UP = `${$prefix}LIS_UP`;
const KERNEL_DISCONNECTED = `${$prefix}KERNEL_DISCONNECTED`;
const KERNEL_CONNECTED = `${$prefix}KERNEL_CONNECTED`;
const SET_SYSTEM_NOTIFICATIONS_STATUS = `${$prefix}SET_SYSTEM_NOTIFICATIONS_STATUS`;
const MODAL_STATE_SYSTEM_NOTIFICATIONS = `${$prefix}MODAL_STATE_SYSTEM_NOTIFICATIONS`;

export {
    SET_SYSTEM_NOTIFICATIONS_STATUS,
    MODAL_STATE_SYSTEM_NOTIFICATIONS,
    CREATE_ACCOUNT,
    SUCCESS_CREATE_NEW_ACCOUNT,
    ERROR_CREATE_NEW_ACCOUNT,
    SET_LIGHTNING_ID,
    LOGIN_ACCOUNT,
    ERROR_AUTH_ON_SERVER,
    START_INIT_ACCOUNT,
    FINISH_INIT_ACCOUNT,
    LOGOUT_ACCOUNT,
    SUCCESS_LOGOUT_ACCOUNT,
    START_LOGOUT,
    FINISH_LOGOUT,
    ERROR_CONNECT_KERNEL,
    SUCCESS_CONNECT_KERNEL,
    SUCCESS_SIGN_MESSAGE,
    SET_CONNECTED_KERNEL_CONNECT_INDICATOR,
    SET_DISCONNECTED_KERNEL_CONNECT_INDICATOR,
    SET_PEERS,
    ERROR_PEERS,
    ADD_BITCOIN_ACCOUNT,
    SUCCESS_SEND_BTC_TO_ADDRESS,
    ERROR_SEND_BTC_TO_ADDRESS,
    SUCCESS_GENERATE_QR_CODE,
    SET_BITCOIN_MEASURE,
    CORRECT_LIGHTNING_ID,
    INCORRECT_LIGHTNING_ID,
    UNDEFINED_LIGHTNING_ID,
    START_VALIDATING_LIGHTNING_ID,
    END_VALIDATING_LIGHTNING_ID,
    INCORRECT_PAYMENT_AMOUNT,
    CORRECT_PAYMENT_AMOUNT,
    UNDEFINED_PAYMENT_AMOUNT,
    SET_MAXIMUM_PAYMENT,
    SUCCESS_CHECK_BALANCE,
    ERROR_CHECK_BALANCE,
    SET_LIS_STATUS,
    LIS_NONE,
    LIS_DOWN,
    LIS_UP,
    KERNEL_DISCONNECTED,
    KERNEL_CONNECTED,
};
