const $prefix = "app/streamPayments/";
const CHANGE_STREAM_PARTS_PAID = `${$prefix}CHANGE_STREAM_PARTS_PAID`;
const CHANGE_STREAM_PARTS_PENDING = `${$prefix}CHANGE_STREAM_PARTS_PENDING`;
const PREPARE_STREAM_PAYMENT = `${$prefix}PREPARE_STREAM_PAYMENT`;
const STREAM_PAYMENT_FINISHED = "end";
const STREAM_PAYMENT_PAUSED = "pause";
const STREAM_PAYMENT_STREAMING = "run";
const MODAL_STATE_STREAM_PAYMENT_DETAILS = `${$prefix}MODAL_STATE_STREAM_PAYMENT_DETAILS`;
const MODAL_STATE_EDIT_STREAM_PAYMENT = `${$prefix}MODAL_STATE_EDIT_STREAM_PAYMENT`;
const MODAL_STATE_ACTIVE_RECURRING_WARNING = `${$prefix}MODAL_STATE_ACTIVE_RECURRING_WARNING`;
const ADD_STREAM_PAYMENT_TO_LIST = `${$prefix}ADD_STREAM_PAYMENT_TO_LIST`;
const SET_STREAM_PAYMENTS = `${$prefix}SET_STREAM_PAYMENTS`;
const SET_CURRENT_STREAM = `${$prefix}SET_CURRENT_STREAM`;
const UPDATE_STREAM_PAYMENT = `${$prefix}UPDATE_STREAM_PAYMENT`;

export {
    CHANGE_STREAM_PARTS_PAID,
    CHANGE_STREAM_PARTS_PENDING,
    PREPARE_STREAM_PAYMENT,
    STREAM_PAYMENT_FINISHED,
    STREAM_PAYMENT_PAUSED,
    STREAM_PAYMENT_STREAMING,
    MODAL_STATE_STREAM_PAYMENT_DETAILS,
    MODAL_STATE_EDIT_STREAM_PAYMENT,
    MODAL_STATE_ACTIVE_RECURRING_WARNING,
    ADD_STREAM_PAYMENT_TO_LIST,
    SET_STREAM_PAYMENTS,
    SET_CURRENT_STREAM,
    UPDATE_STREAM_PAYMENT,
};
