const $prefix = "app/streamPayments/";
const SET_STREAM_CURRENT_ITERATION = `${$prefix}SET_STREAM_CURRENT_ITERATION`;
const SET_STREAM_PAYMENT_STATUS = `${$prefix}SET_STREAM_PAYMENT_STATUS`;
const PREPARE_STREAM_PAYMENT = `${$prefix}PREPARE_STREAM_PAYMENT`;
const STREAM_PAYMENT_FINISHED = `${$prefix}STREAM_PAYMENT_FINISHED`;
const STREAM_PAYMENT_PAUSED = `${$prefix}STREAM_PAYMENT_PAUSED`;
const STREAM_PAYMENT_STREAMING = `${$prefix}STREAM_PAYMENT_STREAMING`;
const MODAL_STATE_STREAM_PAYMENT_DETAILS = `${$prefix}MODAL_STATE_STREAM_PAYMENT_DETAILS`;
const ADD_STREAM_PAYMENT_TO_LIST = `${$prefix}ADD_STREAM_PAYMENT_TO_LIST`;
const SET_STREAM_PAYMENTS = `${$prefix}SET_STREAM_PAYMENTS`;

export {
    SET_STREAM_CURRENT_ITERATION,
    SET_STREAM_PAYMENT_STATUS,
    PREPARE_STREAM_PAYMENT,
    STREAM_PAYMENT_FINISHED,
    STREAM_PAYMENT_PAUSED,
    STREAM_PAYMENT_STREAMING,
    MODAL_STATE_STREAM_PAYMENT_DETAILS,
    ADD_STREAM_PAYMENT_TO_LIST,
    SET_STREAM_PAYMENTS,
};
