const $prefix = "app/streamPayments/";
const STREAM_CURRENT_SEC = `${$prefix}STREAM_CURRENT_SEC`;
const SET_STREAM_PAGE = `${$prefix}SET_STREAM_PAGE`;
const STREAM_PAYMENT_STATUS = `${$prefix}STREAM_PAYMENT_STATUS`;
const STREAM_PAYMENT_SUCCESS_FINISH = `${$prefix}STREAM_PAYMENT_SUCCESS_FINISH`;
const STREAM_PAYMENT_FAIL_FINISH = `${$prefix}STREAM_PAYMENT_FAIL_FINISH`;
const STREAM_PAYMENT_PREPARE = `${$prefix}STREAM_PAYMENT_PREPARE`;
const STREAM_PAYMENT_UPDATE = `${$prefix}STREAM_PAYMENT_UPDATE`;
const STREAM_PAYMENT_DELETE = `${$prefix}STREAM_PAYMENT_DELETE`;
const DELETED_STREAM_PAYMENT = `${$prefix}DELETED_STREAM_PAYMENT`;
const FINISHED_STREAM_PAYMENT = `${$prefix}FINISHED_STREAM_PAYMENT`;
const STREAM_PAYMENT_PAUSE = `${$prefix}STREAM_PAYMENT_PAUSE`;
const STREAM_PAYMENT_STREAMING = `${$prefix}STREAM_PAYMENT_STREAMING`;
const MODAL_STATE_STREAM = `${$prefix}MODAL_STATE_STREAM`;
const MODAL_STATE_STREAM_PAYMENT_DETAILS = `${$prefix}MODAL_STATE_STREAM_PAYMENT_DETAILS`;
const ADD_STREAM_TO_LIST = `${$prefix}ADD_STREAM_TO_LIST`;
const SET_STREAMS = `${$prefix}SET_STREAMS`;

export {
    STREAM_CURRENT_SEC,
    SET_STREAM_PAGE,
    STREAM_PAYMENT_STATUS,
    STREAM_PAYMENT_SUCCESS_FINISH,
    STREAM_PAYMENT_FAIL_FINISH,
    STREAM_PAYMENT_PREPARE,
    STREAM_PAYMENT_UPDATE,
    STREAM_PAYMENT_DELETE,
    DELETED_STREAM_PAYMENT,
    FINISHED_STREAM_PAYMENT,
    STREAM_PAYMENT_PAUSE,
    STREAM_PAYMENT_STREAMING,
    MODAL_STATE_STREAM,
    MODAL_STATE_STREAM_PAYMENT_DETAILS,
    ADD_STREAM_TO_LIST,
    SET_STREAMS,
};
