const $prefix = "app/contacts/";
const ADD_CONTACT = `${$prefix}ADD_CONTACT`;
const MODAL_STATE_DELETE_CONTACT = `${$prefix}MODAL_STATE_DELETE_CONTACT`;
const MODAL_STATE_EDIT_CONTACT = `${$prefix}MODAL_STATE_EDIT_CONTACT`;
const MODAL_STATE_NEW_CONTACT = `${$prefix}MODAL_STATE_NEW_CONTACT`;
const PREPARE_NEW_CONTACT = `${$prefix}PREPARE_NEW_CONTACT`;
const SET_CONTACTS = `${$prefix}SET_CONTACTS`;
const SET_CONTACTS_SEARCH = `${$prefix}SET_CONTACTS_SEARCH`;
const SET_CURRENT_CONTACT = `${$prefix}SET_CURRENT_CONTACT`;
const UPDATE_CURRENT_CONTACT = `${$prefix}UPDATE_CURRENT_CONTACT`;
const NEW_CONTACT_ADDED = `${$prefix}NEW_CONTACT_ADDED`;

export {
    ADD_CONTACT,
    MODAL_STATE_DELETE_CONTACT,
    MODAL_STATE_EDIT_CONTACT,
    MODAL_STATE_NEW_CONTACT,
    PREPARE_NEW_CONTACT,
    SET_CONTACTS,
    SET_CONTACTS_SEARCH,
    SET_CURRENT_CONTACT,
    UPDATE_CURRENT_CONTACT,
    NEW_CONTACT_ADDED,
};
