const $prefix = "app/filter/";
const SET_ONCHAIN_FILTER_PART = `${$prefix}SET_ONCHAIN_FILTER_PART`;
const SET_REGULAR_FILTER_PART = `${$prefix}SET_REGULAR_FILTER_PART`;
const SET_RECURRING_FILTER_PART = `${$prefix}SET_RECURRING_FILTER_PART`;
const CLEAR_ALL_FILTERS = `${$prefix}CLEAR_ALL_FILTERS`;
const INCOMING_PAYMENT = "Income";
const OUTGOING_PAYMENT = "Outcome";
const TYPE_REGULAR = "Regular";
const TYPE_RECURRING = "Recurring";
const TYPE_ONCHAIN = "Onchain";
const ALL_PAYMENTS = "All";
const ANTE_MERIDIEM = "AM";
const POST_MERIDIEM = "PM";

export {
    SET_ONCHAIN_FILTER_PART,
    SET_REGULAR_FILTER_PART,
    SET_RECURRING_FILTER_PART,
    CLEAR_ALL_FILTERS,
    INCOMING_PAYMENT,
    OUTGOING_PAYMENT,
    TYPE_REGULAR,
    TYPE_RECURRING,
    TYPE_ONCHAIN,
    ALL_PAYMENTS,
    ANTE_MERIDIEM,
    POST_MERIDIEM,
};
