const $prefix = "app/auth/";
const LOGIN_FORM = `${$prefix}LOGIN_FORM`;
const REGISTRATION_FORM = `${$prefix}REGISTRATION_FORM`;
const RESTORE_WALLET_FORM = `${$prefix}RESTORE_WALLET_FORM`;
const RESTORE_SESSION_FORM = `${$prefix}RESTORE_SESSION_FORM`;
const SET_CURRENT_FORM = `${$prefix}SET_CURRENT_FORM`;
const SET_TEMP_USERNAME = `${$prefix}SET_TEMP_USERNAME`;
const SET_PASSWORD = `${$prefix}SET_PASSWORD`;
const REGISTRATION_STEP_INIT = `${$prefix}REGISTRATION_STEP_INIT`;
const REGISTRATION_STEP_SEED_DISPLAY = `${$prefix}REGISTRATION_STEP_SEED_DISPLAY`;
const REGISTRATION_STEP_SEED_VERIFY = `${$prefix}REGISTRATION_STEP_SEED_VERIFY`;
const SET_REGISTRATION_STEP = `${$prefix}SET_REGISTRATION_STEP`;
const RESTORE_STEP_SEED = `${$prefix}RESTORE_STEP_SEED`;
const RESTORE_STEP_USER_PASS = `${$prefix}RESTORE_STEP_USER_PASS`;
const RESTORE_STEP_USE_WALLET_DATA = `${$prefix}RESTORE_STEP_USE_WALLET_DATA`;
const RESTORE_STEP_SELECT_METHOD = `${$prefix}RESTORE_STEP_SELECT_METHOD`;

export {
    LOGIN_FORM,
    REGISTRATION_FORM,
    RESTORE_WALLET_FORM,
    RESTORE_SESSION_FORM,
    SET_CURRENT_FORM,
    SET_TEMP_USERNAME,
    SET_PASSWORD,
    REGISTRATION_STEP_INIT,
    REGISTRATION_STEP_SEED_DISPLAY,
    REGISTRATION_STEP_SEED_VERIFY,
    SET_REGISTRATION_STEP,
    RESTORE_STEP_SEED,
    RESTORE_STEP_USER_PASS,
    RESTORE_STEP_USE_WALLET_DATA,
    RESTORE_STEP_SELECT_METHOD,
};
