const $prefix = "app/app/";
const CLOSE_MODAL_STATE = `${$prefix}CLOSE_MODAL_STATE`;
const PROFILE_CHANGE_PASS_MODAL_STATE = `${$prefix}PROFILE_CHANGE_PASS_MODAL_STATE`;
const MODAL_STATE_FORCE_LOGOUT = `${$prefix}MODAL_STATE_FORCE_LOGOUT`;
const MODAL_STATE_LEGAL = `${$prefix}MODAL_STATE_LEGAL`;
const DEEP_LINK_LIGHTNING_MODAL_STATE = `${$prefix}DEEP_LINK_LIGHTNING_MODAL_STATE`;
const LOGOUT_MODAL_STATE = `${$prefix}LOGOUT_MODAL_STATE`;
const SET_MODAL_STATE = `${$prefix}SET_MODAL_STATE`;
const USD_PER_BTC = `${$prefix}USD_PER_BTC`;
const DB_OPENED = `${$prefix}DB_OPENED`;
const DB_CLOSED = `${$prefix}DB_CLOSED`;
const DB_CLOSING = `${$prefix}DB_CLOSING`;
const DB_SET_STATUS = `${$prefix}DB_SET_STATUS`;
const SUCCESS_SEND_PAYMENT = `${$prefix}SUCCESS_SEND_PAYMENT`;
const FAIL_SEND_PAYMENT = `${$prefix}FAIL_SEND_PAYMENT`;
const SET_FORCE_LOGOUT_ERROR = `${$prefix}SET_FORCE_LOGOUT_ERROR`;
const SET_APP_AS_DEFAULT_STATUS = `${$prefix}SET_APP_AS_DEFAULT_STATUS`;
const SET_PEER_PORT = `${$prefix}SET_PEER_PORT`;

export {
    CLOSE_MODAL_STATE,
    PROFILE_CHANGE_PASS_MODAL_STATE,
    SET_FORCE_LOGOUT_ERROR,
    MODAL_STATE_LEGAL,
    SET_MODAL_STATE,
    USD_PER_BTC,
    LOGOUT_MODAL_STATE,
    MODAL_STATE_FORCE_LOGOUT,
    DEEP_LINK_LIGHTNING_MODAL_STATE,
    DB_OPENED,
    DB_CLOSED,
    DB_SET_STATUS,
    DB_CLOSING,
    SUCCESS_SEND_PAYMENT,
    FAIL_SEND_PAYMENT,
    SET_APP_AS_DEFAULT_STATUS,
    SET_PEER_PORT,
};
