const $prefix = "app/channels/";
const CHANNEL_STATUS_ACTIVE = `${$prefix}CHANNEL_STATUS_ACTIVE`;
const CHANNEL_STATUS_NOT_ACTIVE = `${$prefix}CHANNEL_STATUS_NOT_ACTIVE`;
const CHANNEL_STATUS_PENDING = `${$prefix}CHANNEL_STATUS_PENDING`;
const SET_CHANNELS = `${$prefix}SET_CHANNELS`;
const ERROR_CHANNELS = `${$prefix}ERROR_CHANNELS`;
const START_CREATE_NEW_CHANNEL = `${$prefix}START_CREATE_NEW_CHANNEL`;
const SUCCESS_CREATE_NEW_CHANNEL = `${$prefix}SUCCESS_CREATE_NEW_CHANNEL`;
const ERROR_CREATE_NEW_CHANNEL = `${$prefix}ERROR_CREATE_NEW_CHANNEL`;
const END_CREATE_NEW_CHANNEL = `${$prefix}END_CREATE_NEW_CHANNEL`;
const NEW_CHANNEL_PREPARING = `${$prefix}NEW_CHANNEL_PREPARING`;
const CLEAR_NEW_CHANNEL_PREPARING = `${$prefix}CLEAR_NEW_CHANNEL_PREPARING`;
const MODAL_STATE_NEW_CHANNEL = `${$prefix}MODAL_STATE_NEW_CHANNEL`;
const MODAL_STATE_DELETE_CHANNEL = `${$prefix}MODAL_STATE_DELETE_CHANNEL`;
const MODAL_STATE_EDIT_CHANNEL = `${$prefix}MODAL_STATE_EDIT_CHANNEL`;
const MODAL_STATE_FORCE_DELETE_CHANNEL = `${$prefix}MODAL_STATE_FORCE_DELETE_CHANNEL`;
const SET_CURRENT_CHANNEL = `${$prefix}SET_CURRENT_CHANNEL`;
const CLEAR_CURRENT_CHANNEL = `${$prefix}CLEAR_CURRENT_CHANNEL`;
const UPDATE_CREATE_TUTORIAL_STATUS = `${$prefix}UPDATE_CREATE_TUTORIAL_STATUS`;
const MODAL_WARNING = `${$prefix}MODAL_WARNING`;
const SHOW = `${$prefix}SHOW`;
const PENDING = `${$prefix}PENDING`;
const HIDE = `${$prefix}HIDE`;
const ADD_TO_DELETE = `${$prefix}ADD_TO_DELETE`;
const REMOVE_FROM_DELETE = `${$prefix}REMOVE_FROM_DELETE`;

export {
    CHANNEL_STATUS_ACTIVE,
    CHANNEL_STATUS_NOT_ACTIVE,
    CHANNEL_STATUS_PENDING,
    SET_CHANNELS,
    ERROR_CHANNELS,
    START_CREATE_NEW_CHANNEL,
    SUCCESS_CREATE_NEW_CHANNEL,
    ERROR_CREATE_NEW_CHANNEL,
    END_CREATE_NEW_CHANNEL,
    NEW_CHANNEL_PREPARING,
    CLEAR_NEW_CHANNEL_PREPARING,
    MODAL_STATE_NEW_CHANNEL,
    MODAL_STATE_DELETE_CHANNEL,
    MODAL_STATE_EDIT_CHANNEL,
    MODAL_STATE_FORCE_DELETE_CHANNEL,
    SET_CURRENT_CHANNEL,
    CLEAR_CURRENT_CHANNEL,
    UPDATE_CREATE_TUTORIAL_STATUS,
    MODAL_WARNING,
    SHOW,
    PENDING,
    HIDE,
    ADD_TO_DELETE,
    REMOVE_FROM_DELETE,
};
