const $prefix = "app/lightning/";
const CLEAR_SINGLE_PAYMENT_DETAILS = `${$prefix}CLEAR_SINGLE_PAYMENT_DETAILS`;
const ERROR_PAYMENT = `${$prefix}ERROR_PAYMENT`;
const FAILED_PAYMENT_TYPE = `${$prefix}FAILED_PAYMENT_TYPE`;
const INVOICE_TYPE = `${$prefix}INVOICE_TYPE`;
const MODAL_STATE_PAYMENT_DETAILS = `${$prefix}MODAL_STATE_PAYMENT_DETAILS`;
const MODAL_STATE_CHANNEL_WARNING = `${$prefix}MODAL_STATE_CHANNEL_WARNING`;
const PAYMENT_PREPARING = `${$prefix}PAYMENT_PREPARING`;
const PAYMENT_TYPE = `${$prefix}PAYMENT_TYPE`;
const PENDING_PAYMENT = `${$prefix}PENDING_PAYMENT`;
const SET_HISTORY = `${$prefix}SET_HISTORY`;
const SUCCESS_PAYMENT = `${$prefix}SUCCESS_PAYMENT`;
const PAYMENT_REQUEST_CREATOR = `${$prefix}PAYMENT_REQUEST_CREATOR`;
const PAYMENT_REQUEST_ERROR_CREATOR = `${$prefix}PAYMENT_REQUEST_ERROR_CREATOR`;
const SET_EXTERNAL_PAYMENT_REQUEST = `${$prefix}SET_EXTERNAL_PAYMENT_REQUEST`;

export {
    CLEAR_SINGLE_PAYMENT_DETAILS,
    ERROR_PAYMENT,
    FAILED_PAYMENT_TYPE,
    INVOICE_TYPE,
    MODAL_STATE_PAYMENT_DETAILS,
    MODAL_STATE_CHANNEL_WARNING,
    PENDING_PAYMENT,
    PAYMENT_PREPARING,
    PAYMENT_TYPE,
    SET_HISTORY,
    SUCCESS_PAYMENT,
    PAYMENT_REQUEST_CREATOR,
    PAYMENT_REQUEST_ERROR_CREATOR,
    SET_EXTERNAL_PAYMENT_REQUEST,
};
